### ISSUE TITLE
Lost files

### ISSUE THREAD

**Issue by linyute** [jbbi/repositorywrapper#1]
Hi, 
I clone the lasted commit, and the solution compiles fail.

Project: RepositoryWrapper.Test.Dapper
Unable to find source file:
ConnectionTransactionFactory.cs
UnitOfWorkTest.cs

**Comment by binard** [comment]
Hi,

It' should work now. I recover the lost files and just push it.

**Comment by linyute** [comment]
Hi,
It works, Thank you.
You save my time.
